services:
  - type: web
    name: healthinfo-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn healthinfo.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: healthinfo-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: healthinfo-backend.onrender.com
databases:
  - name: healthinfo-db
    databaseName: healthinfo
    user: healthuser
